compile:
	g++ -o lab6 main.cpp CTask.cpp -I.

testfind:
	./lab6 find 3 input output 

testcount:
	./lab6 count 4 input output

testsort:
	./lab6 sort input output

testall: testfind testcount testsort
